### ISSUE TITLE
Use similar spacing for login and register pages

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#360]
Login and register page should work in a pretty similar way, atm spacing is not like that.

![image](https://user-images.githubusercontent.com/6463001/137551993-d5718f4e-92d7-4b5c-ba65-d83078453498.png)
![image](https://user-images.githubusercontent.com/6463001/137552297-7613f8e7-1a84-4349-b767-f81f60e32d31.png)

**Comment by leonardobrito** [comment]
Well, I believe that align-items at the center is better for all screen, so what we need to grant is the consistent spacing between the elements.

I have looked at the code and maybe the issue is that register page use `display: grid;` and login page use `display: flex;`

Maybe you can see if just changing the `display` fix the issue @jayeclark 😃

**Comment by iurynogueira** [comment]
The pages are with `display: flex` and `align-items: center` however the register page is bigger. To align this you can remove the `align-items` and add `magin-top: x%` to pages.

**Comment by jayeclark** [comment]
@leonardobrito OK, I understand. The two forms have different elements so it stands to reason that they'd be different heights overall (2 fields vs 3, subtitle vs no subtitle.) Its not a problem to fix it by fiddling with the form spacing to ensure they're the same overall dimensions, but the `align-items: center` actually makes the content overflow up off the top of the page for small viewport heights.

**Current at vh = 500px (align-items center)**
<img width="400" alt="Screen Shot 2021-10-15 at 6 00 02 PM" src="https://user-images.githubusercontent.com/84106309/137558433-e04ff5f2-0385-42d2-b621-68c5b83e39e4.png">
  
**Proposed solution at vh = 500px (align-items start)**
<img width="400" alt="Screen Shot 2021-10-15 at 6 00 20 PM" src="https://user-images.githubusercontent.com/84106309/137558451-bd71b4dc-8848-4e5f-a814-bba0bed98d1b.png">
  
Should I also make the two pages responsive so that they look OK for small viewport heights?

**Comment by jayeclark** [comment]
Yeah @iurynogueira that's what I was just about to submit.
